let all_products = [
  {
    id: 1,
    category: "bottoms",
    image: 'https://via.placeholder.com/200',
    name: 'Leopard-Trim Flare Leg',
    price: '$17.49',
    isExclusive: true,
  },
  {
    id: 2,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Leopard Print Flare Pants',
    price: '$17.49',
    oldPrice: '$24.99',
    discount: '30% OFF',
    isExclusive: true,
  },
  {
    id: 3,
    category: "outerwear",
    image: 'https://via.placeholder.com/200',
    name: 'Jacquard Baroque Mini Skirt',
    price: '$13.99',
    isExclusive: false,
  },
  {
    id: 4,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Fleece Drawstring Sweatshorts',
    price: '$12.59',
    isExclusive: false,
  },
  {
    id: 5,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Bow Bodycon Maxi Skirt',
    price: '$17.49',
    isExclusive: true,
  },
  {
    id: 6,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Bethel Denim Mini Skirt',
    price: '$17.49',
    oldPrice: '$24.99',
    discount: '30% OFF',
    isExclusive: true,
  },
  {
    id: 7,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Striped Twill Pleated Mini Skirt',
    price: '$17.49',
    oldPrice: '$24.99',
    discount: '30% OFF',
    isExclusive: true,
  },
  {
    id: 8,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'High-Rise Corduroy Flare Pants',
    price: '$24.49',
    isExclusive: true,
  },
  {
    id: 9,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Ribbed Knit Crop Top',
    price: '$10.99',
    isExclusive: false,
  },
  {
    id: 10,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Printed Wrap Skirt',
    price: '$15.49',
    isExclusive: false,
  },
  {
    id: 11,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Plaid Pleated Skirt',
    price: '$18.99',
    isExclusive: false,
  },
  {
    id: 12,
    category: "tops",
    image: 'https://via.placeholder.com/200',
    name: 'Mesh Insert Bodycon Dress',
    price: '$22.49',
    oldPrice: '$29.99',
    discount: '30% OFF',
    isExclusive: true,
  },
];

export default all_products;